### ISSUE TITLE
RS256

### ISSUE THREAD

**Issue by shtefanntz** [auth0/auth0-webapi-js-sample#5]
Greetings,

Can you add some support for the case when the hashing algorithm is RS256, please?

Thanks!

**Comment by jerriep** [comment]
@shtefanntz Please refer to either our OWIN or ASP.NET Core quickstarts:

* https://auth0.com/docs/quickstart/backend/webapi-owin
* https://auth0.com/docs/quickstart/backend/aspnet-core-webapi

Both of these show how to configure the JWT middleware to use either RS256 or HS256. 

I suggest that you migrate your existing ASP.NET app to use the OWIN pipeline. You can refer to this MS document to see how you can add OWIN to an existing app:
https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana

**Comment by shtefanntz** [comment]
My bad, I didn't specify that i wanted some help for a System.Web project. Nonetheless, a good step would be to update the project to use the OWIN pipeline.

Thanks!

**Comment by jerriep** [comment]
Yes, please. There is much better support for middleware in OWIN :)
