### ISSUE TITLE
Signature Verification Exception Issue

### ISSUE THREAD

**Issue by kanwal019** [auth0/auth0-webapi-js-sample#6]
Hi,

I am receiving a Signature Verification Exception while verifying the JWT, which shows the difference between expected and received values of the JWT Signature.

I have checked on the JWT.io, the signature is verified successfully.

**Comment by jerriep** [comment]
Hi,

Can you please provide more information?

* What technologies are you using?
* Can you give a sample of the code which is failing?

The information you provided is unfortunately too limited for me to give you any sort of assistance.

**Comment by kanwal019** [comment]
I am using C# and JavaScript with lock to authenticate a WebApi.

This is the code(_App_Start\JsonWebToken.cs_) which is failing - 
` var payloadJson = JWT.JsonWebToken.Decode(token, Convert.FromBase64String(secretKey), verify: true);`

This is called from the following code(_App_Start\JsonWebTokenValidationHandler.cs_) -

```
Thread.CurrentPrincipal = JsonWebToken.ValidateToken(
                        token,
                        secret,
                        audience: this.Audience,
                        checkExpiration: true,
                        issuer: this.Issuer);
                    
                    if (HttpContext.Current != null)
                    {
                        HttpContext.Current.User = Thread.CurrentPrincipal;
                    }
```

A JWT.SignatureVerificationException is catched in the above code as described previously.

**Comment by jerriep** [comment]
Can you please post the actual JWT here, so I can inspect it?

Also, this is a very old sample. Can you please tell me what version of ASP.NET Web API you are using? Also, are you using OWIN in your project?

**Comment by kanwal019** [comment]
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3N3b3JrNS5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTA5MzAwNTc4MzAwODIzODkyNTQiLCJhdWQiOiJLcnF2QUJZWGdlRHllanB4cGpPSTlzRG5IVG1OdUx4VyIsImV4cCI6MTQ5Mzc1MzAyNCwiaWF0IjoxNDkzNzE3MDI0fQ.Bf52qEfleyXNn1EEZFZEAULvk4eXSSxHCQFjX3Bm1qg`

This is the token generated by the TryRetrieveToken function. I don't think OWIN is used in this project.

**Comment by kanwal019** [comment]
@jerriep Thanks for your help. The issue is resolved.

In the project "IsSecretBase64Encoded" was defaulted to true. Changing it to false validates the token correctly.
